name: Selenium Tests

on:
  push:
    branches: [main]  # run workflow when code is pushed to main branch
  pull_request:
    branches: [main]  # run workflow on PRs targeting main

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Install Chrome and Chromedriver
      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          chrome-version: 'latest'

      # Step 5: Run Selenium tests in headless mode
      - name: Run pytest
        run: |
          pytest tests/ --html=reports/report.html --self-contained-html

      # Step 6: Upload HTML report as artifact
      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: selenium-html-report
          path: reports/report.html
